### ISSUE TITLE
FPS Confused

### ISSUE THREAD

**Issue by 18128381510** [UCDvision/compact3d#13]
Great job. But I am a bit confused. compactGS can reduce memory, but how does it improve rendering speed (FPS)? compactGS represents n Gaussians with m cluster centers (m < n), but during rendering, m cluster centers replicate n Gaussians for rendering, so the number of Gaussians during rendering remains n. Doesn't this mean that the computational workload remains unchanged? Therefore, I am quite puzzled as to why the paper mentions an improvement in rendering speed ?

**Comment by klnavaneet** [comment]
Hi @18128381510. You are right, just using vector quantization will not have much impact on rendering speed. The reason for increase in FPS is the reduction in the number of Gaussians in a scene due to opacity regularization. The regularization forces a lot of Gaussians to be highly transparent which are then pruned without impacting rendering quality. Since the number of Gaussians reduces by 2-3x, we see a similar boost in speed.

**Comment by 18128381510** [comment]
Thanks
