### ISSUE TITLE
quant_params sh dc rot sc?

### ISSUE THREAD

**Issue by runningpp** [UCDvision/compact3d#3]
The default "quant_params" is [sh dc rot sc]. I found the size of the model not still large with the default quant_params. It may be not the parameters of the paper. Can you provide the quant_params of the paper?

**Comment by klnavaneet** [comment]
Hi. We have modified the code to save and load the compressed quantized version of the model. Let me know if you still face any issues. The file size will be slightly more than the numbers reported in the paper since we have not included run-length encoding for the indices, so indices of one extra parameter needs to be saved. 

Note: there was an error in the "quant_parameters" argument. It must be [sh dc rot scale], not [sh dc rot sc]. We have updated this in the run.sh file

**Comment by klnavaneet** [comment]
Closing the issue for now since it has been resolved. Feel free to reopen it if needed.
